### ISSUE TITLE
Build errors on simulator

### ISSUE THREAD

**Issue by just-jason** [snebragd/stringent#1]
I tried to setp the simulator today, and after installing clang, I ran ./build.sh.
and i got a few errors

In file included from sim.c:3:
In file included from /usr/include/stdio.h:27:
In file included from /usr/include/x86_64-linux-gnu/bits/libc-header-start.h:33:
/usr/include/features.h:184:3: warning: "_BSD_SOURCE and _SVID_SOURCE are
      deprecated, use _DEFAULT_SOURCE" [-W#warnings]
# warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
  ^
In file included from sim.c:173:
/tmp/data.ino:53:7: error: use of undeclared identifier 'Serial'
      SER_PRINT("Found: ");      
      ^
../plotter/MachineDefs.h:5:22: note: expanded from macro 'SER_PRINT'
#define SER_PRINT(X) Serial.print((X))
                     ^
In file included from sim.c:173:
/tmp/data.ino:54:7: error: use of undeclared identifier 'Serial'
      SER_PRINTLN(svgName);   
   
Am I missing something simple here? it almost looks like a missing library, but I can not see what it could be

**Comment by snebragd** [comment]
Hej!

You need to not define SERIAL_DEBUG (in machine_defs.h). Serial debugging doesn’t make sense in the simulator... :-)

Good luck!

/Fredrik

**Comment by just-jason** [comment]
Thanks, that did the job. Looks good now
